### PR TITLE
Fix up line endings (for linux bottle) and remove extra end of line character

### PR DESCRIPTION
**Pull request by S-Stephen**
Hi Eric,

In taking a look at your app, to get running on our systems (Linux Python 3.5) I had to fix up the line endings from what appeared to be a DOS file, as this seemed to upset the bottle libraries (%> must be the first characters on the line to close the section).

The code also seemed to be failing because it didn't like the new line and indentation before the for command.

I played with releasing this behind other services hence also including the ability to change host name and port via environment variables.

After doing these things all looks good. Is there any chance you could merge these?

Thanks in advance

Stephen

### CODE REVIEW

**Comment by eric-wieser** [comment]
The bug is actually upstream in bottle (bottlepy/bottle#643), and will go away if you install the bleeding-edge bottle

**Comment by eric-wieser** [comment]
And then the `for` thing looks like the issue I fixed in (bottlepy/bottle#690),

**Comment by S-Stephen** [comment]
Hi Eric,

Would there be any chance of get the PORT and HOST options merged if I we to generate a separate pull request for these.

Also how about the Procfile?

TIA
Stephen

**Comment by eric-wieser** [comment]
Host and port, and procfile, seem sane.

Having said that, the more common way to run a python server is to load the module into an external server executable, ie `gunicorn mymainfile:app --bind=$HOST:$PORT`

For that matter, you can hook straight into apache with `mod_wsgi`

**Comment by S-Stephen** [comment]
Thanks

I prefer (and should use) the gunicorn solution though would this mean that I would need to take the configuration of '/cued-labs' subdirectory outside of the python app?  this might not be possible with my environment is there a way of handling the request for $HOST:$PORT/cued-labs via gunicorn?

Also I'd prefer that the changes for table.tpl be merged rather than needing to import a bleeding edge version of bottle as the requirements.txt does state 0.12.8, or wait for the 0.12.9 version, will they break the app when upgrading to 0.12.9?

Stephen
Stephen

**Comment by eric-wieser** [comment]
Yes, the `/cued-labs` subdirectory is a hack to allow me to host it on srcf behind an apache I have insufficient control over, and should probably be hidden under a command line flag. I'll do that at some point.

Reading your post again, I'm not entirely sure what you mean by _"is there a way of handling the request for $HOST:$PORT/cued-labs via gunicorn"_

0.12.9 doesn't look like it will ever come, and 0.13.0 is taking a while to release. No, the upgrade will not break things, as I've been developing with the bleeding edge version anyway.

Would an absolute commit reference in requirements.txt be amenable to you?

**Comment by eric-wieser** [comment]
Actually, you can already choose to serve at either location:

```
$ gunicorn main:app --bind=localhost:8090
$ wget localhost:8090

$ gunicorn main:root --bind=localhost:8091
$ wget localhost:8091/cued-labs
```

**Comment by eric-wieser** [comment]
I'm not too keen on including the gunicorn dependency here - there any many different ways to run python WSGI servers, and enforcing any one on the user seems unecessary. You can also use bottle directly to launch these servers:

```
python3 -m bottle main:app --bind=site.com:80
```

**Comment by S-Stephen** [comment]
If an absolute commit reference would mean that the correct version is installed when I release that would be fine.

wrt main.py sorry I didn't read the main:root option

The mods to Procfile were also made to facilitate the deployment on the platform sure I could manually put one in place but to do everything by a pull would be more obvious and convenient

**Comment by eric-wieser** [comment]
I've updated the `requirements.txt` file to use the latest bottle.

Since host and port are specifiable from any command line WSGI tool, I'm not in favor of reading environment variables any more.

**Comment by S-Stephen** [comment]
That's great, I'm a little nervous using a dev branch and do get some form of warning when pip installs it (about finding a particular commit) but not sure on the actual issue. However if I can live with this then the inclusion of this immediately eliminates the need for changes I made to table.py

Agreed about the changes main.py, reading ENV variables is redundant given I can manage this via the wrapping Procfile, I just need to figure out how to manage the Procfile in my deployment process.

**Comment by eric-wieser** [comment]
Perhaps the solution is your own repository containing a Procfile and my repo as a submodule? That way, you can choose when to update your copy independently of changing your environment

**Comment by eric-wieser** [comment]
FYI, I think there's a been a 12.9 release upon my request that includes the fixes needed here. YMMV.

**Pull request closed without merging**
